version: "3.8"

services:
  dashboard:
    image: ghcr.io/talon04/homelab-dashboard-api:latest
    ports:
      - "5000:5000"
    volumes:
      - ./backend:/app/backend
      - ./frontend:/app/frontend
      - ./backend/config:/app/backend/config
      - /var/run/docker.sock:/var/run/docker.sock
    restart: unless-stopped
